homeassistant:
  name: Casa
  latitude: 45.437164
  longitude: 10.970851
  elevation: 64
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages
config:
hassio:
updater:
discovery:
sun:
dialogflow:
ffmpeg:
media_extractor:
downloader:
  download_dir: www
logbook:
  exclude:
    entities:
      - sensor.speedtest
      - sensor.date_countdown
      - sensor.wunderground
      - sensor.darksky
      - sensor.systemmonitor
    domains:
      - sun
      - ffmpeg
      - camera
      - android_ip_webcam
      - device_tracker
      - intent_script
      - zone
      - weblink
      - history_graph
      - panel_iframe
      - script
      - input_boolean
      - input_number
logger:
  default: critical
  logs:
    custom_components.sensor.broadlink_s1c: debug
    homeassistant.components: info
    homeassistant.components.http: debug
    homeassistant.components.dialogflow: debug
recorder:
  purge_interval: 2
  purge_keep_days: 3
http:
   server_port: 8123
   base_url: !secret base_url_site
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem
   ip_ban_enabled: True
   login_attempts_threshold: 5
   api_password: !secret http_password
   trusted_networks:
     - 127.0.0.1
     - ::1
     - 192.168.1.0/24
     - 192.168.0.0/24
tts:
  - platform: google
    cache: true
    cache_dir: /config/www/vl/voice
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
#  client_id: home-assistant-2
  keepalive: 30
#  protocol: 3.1 


############
# Includes
############
alarm_control_panel: !include includes/alarm.yaml
android_ip_webcam: !include includes/android_ip_webcams.yaml
automation: !include includes/automations.yaml
binary_sensor: !include includes/binary_sensor.yaml
camera: !include includes/cameras.yaml
device_tracker: !include includes/device_trackers.yaml
frontend: !include includes/frontend.yaml
group: !include includes/groups.yaml
history: !include includes/history.yaml
history_graph: !include includes/history_graph.yaml
ifttt: !include includes/ifttt.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_select: !include includes/input_select.yaml
intent_script: !include includes/intent_scripts.yaml
light: !include includes/light.yaml
media_player: !include includes/media_players.yaml
notify: !include includes/notify.yaml
panel_iframe: !include includes/panel_iframes.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
switch: !include includes/switches.yaml
weblink: !include includes/weblinks.yaml
zone: !include includes/zones.yaml
#cloud: !include includes/cloud.yaml
