homeassistant:
  name: Casa
  latitude: 45.437164
  longitude: 10.970851
  elevation: 64
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages
cloud:
  alexa:
    filter:
      include_domains:
 light
#      switch.stairs:
#        display_categories: LIGHT
    entity_config:
#******************************************************************************
#*******************************   LIGHTS  ************************************
#******************************************************************************
      light.tavolino:
        name: tavolino
        description: luce sul tavolo
        display_categories: LIGHT
      light.libreria:
        name: libreria
        description: luce sulla libreria
        display_categories: LIGHT
      light.mobile_tv:
        name: mobile
        description: luce sul mobile tv
        display_categories: LIGHT
      light.retro_tv:
        name: tv
        description: luce dietro la tv
        display_categories: LIGHT
      light.light_desk:
        name: scrivania
        description: luce sulla scrivania
        display_categories: LIGHT
      light.led_strip:
        name: striscia led
        description: luce led
        display_categories: LIGHT
      light.light_kitchen:
        name: lavandino
        description: luce lavandino
        display_categories: LIGHT
      light.light_kitchen_2:
        name: entrata
        description: luce entrata
        display_categories: LIGHT
      light.corridoio_bagno:
        name: bianca
        description: luce bianca nel corridoio
        display_categories: LIGHT
      light.corridoio_porta:
        name: blu
        description: luce blu nel corridoio
        display_categories: LIGHT
      light.tv:
        name: retro tv
        description: luce sul retro della tv
        display_categories: LIGHT
      light.soffitto:
        name: soffitto
        description: luce che punta al soffitto
        display_categories: LIGHT
      light.giardino:
        name: giardino
        description: luce in giardino
        display_categories: LIGHT
      light.camera:
        name: camera da letto
        description: luce sotto il letto
        display_categories: LIGHT
      light.bagno:
        name: bagno
        description: luce in bagno
        display_categories: SWITCH
#******************************************************************************
#*******************************   SCENES  ************************************
#******************************************************************************
      scene.buona_notte:
        name: notte
        description: fai una buona notte
      scene.corridoio_spento:
        name: corridoio
        description: luci nel corridoio
      scene.film:
        name: cinema
        description: luci cinema
      scene.black_alert:
        name: allarme nero
        description: allarme nero immediato
      scene.red_alert:
        name: allarme rosso
        description: scena allarme rosso
      scene.foresta:
        name: foresta
        description: scena foresta
      scene.inverno:
        name: inverno
        description: scena inverno
      scene.oceano:
        name: oceano
        description: scena oceano
      scene.club:
        name: club
        description: scena club
      scene.acquario:
        name: acquario
        description: scena acquario
      scene.hdmi_1:
        name: canale 1
        description: hdmi 1
      scene.hdmi_2:
        name: canale 2
        description: hdmi 2
      scene.hdmi_3:
        name: canale 3
        description: hdmi 3
      scene.nhk:
        name: nhk
        description: canale nhk
      scene.skyuno:
        name: sky one
        description: canale sky one
      scene.skynews:
        name: sky news
        description: canale sky news
#******************************************************************************
#*****************************   SWITCHES  ************************************
#******************************************************************************
      switch.insettivoro:
        name: ventilatore
        description: ventilatore in sala
      switch.tv:
        name: tv
        description: televisione
      switch.accendi_termostato_dashboard_bagno:
        name: scalda il bagno
        description: il termoventilatore in bagno
      switch.accendi_termostato_dashboard_salotto:
        name: scalda il salotto
        description: il termoventilatore in salotto
      switch.accendi_termostato_dashboard_camera:
        name: scalda la camera
        description: il termoventilatore in camera
      switch.tv_volume:
        name: volume tv
        description: volume della tv
      switch.nabaztaglife:
        name: coniglio
        description: nabaztag
#******************************************************************************
#******************************   SCRIPTS  ************************************
#******************************************************************************
      script.apricancello:
        name: cancello
        description: apriti sesamo
#******************************************************************************
#******************************   SENSORS  ************************************
#******************************************************************************
      sensor.dht_humidity:
        name: umidità
#        type: climate
        description: umidità vicino al server
        display_categories: TEMPERATURE_SENSOR
      sensor.dht_temperature:
        name: temperatura
#        type: climate
        description: temperatura vicino al server
        display_categories: TEMPERATURE_SENSOR
#******************************************************************************
config:
updater:
discovery:
sun:
dialogflow:
ffmpeg:
media_extractor:
downloader:
  download_dir: www
logbook:
  exclude:
    entities:
      - sensor.speedtest
      - sensor.date_countdown
      - sensor.wunderground
      - sensor.darksky
      - sensor.systemmonitor
    domains:
      - sun
      - ffmpeg
      - camera
      - android_ip_webcam
      - device_tracker
      - intent_script
      - zone
      - weblink
      - history_graph
      - panel_iframe
      - script
      - input_boolean
      - input_number
logger:
  default: critical
  logs:
    custom_components.sensor.broadlink_s1c: debug
    homeassistant.components: info
    homeassistant.components.http: debug
    homeassistant.components.dialogflow: debug
recorder:
  purge_interval: 2
  purge_keep_days: 3
http:
   server_port: 8123
   base_url: !secret base_url_site
   ip_ban_enabled: True
   login_attempts_threshold: 5
   api_password: !secret http_password
   trusted_networks:
     - 127.0.0.1
     - ::1
     - 192.168.1.0/24
tts:
  - platform: google
    cache: true
    cache_dir: /config/www/vl/voice
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  protocol: 3.1 

############
# Includes
############
alarm_control_panel: !include includes/alarm.yaml
android_ip_webcam: !include includes/android_ip_webcams.yaml
automation: !include includes/automations.yaml
binary_sensor: !include includes/binary_sensor.yaml
camera: !include includes/cameras.yaml
device_tracker: !include includes/device_trackers.yaml
frontend: !include includes/frontend.yaml
group: !include includes/groups.yaml
history: !include includes/history.yaml
history_graph: !include includes/history_graph.yaml
ifttt: !include includes/ifttt.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_select: !include includes/input_select.yaml
intent_script: !include includes/intent_scripts.yaml
light: !include includes/light.yaml
media_player: !include includes/media_players.yaml
notify: !include includes/notify.yaml
panel_iframe: !include includes/panel_iframes.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
switch: !include includes/switches.yaml
weblink: !include includes/weblinks.yaml
zone: !include includes/zones.yaml
