###############################################################################
#
#                              STARTS ADDONS IF STOPPED
#
###############################################################################
#------------------------------------------------------------------------------
automation:
#------------------------------------------------------------------------------
  - alias: "Restart Addons at start"
    trigger:
      platform: homeassistant
      event: start
    action:
      - delay: '00:01:00'
      - service: hassio.addon_restart
        data:
          addon: "core_git_pull"
#******************************************************************************
  - alias: "Start Addons if stopped"
    trigger:
      platform: time_pattern
      minutes: '/5'
      seconds: 00
    action:
      - service: hassio.addon_start
        data:
          addon: "a0d7b954_appdaemon3"
      - service: hassio.addon_start
        data:
          addon: "de3cd379_audio_player"
      - service: hassio.addon_start
        data:
          addon: "core_check_config"
      - service: hassio.addon_start
        data:
          addon: "03d23610_dasshio"
      - service: hassio.addon_start
        data:
          addon: "core_duckdns"
      - service: hassio.addon_start
        data:
          addon: "core_git_pull"
      - service: hassio.addon_start
        data:
          addon: "a0d7b954_ide"
      - service: hassio.addon_start
        data:
          addon: "a0d7b954_logviewer"
      - service: hassio.addon_start
        data:
          addon: "core_mosquitto"
      - service: hassio.addon_start
        data:
          addon: "a0d7b954_pi-hole"
      - service: hassio.addon_start
        data:
          addon: "de3cd379_rfreceiver"
      - service: hassio.addon_start
        data:
          addon: "a0d7b954_ssh"
      - service: hassio.addon_start
        data:
          addon: "core_samba"
#******************************************************************************
