###############################################################################
#
#                                 RING DOORBELL 
#
###############################################################################
#------------------------------------------------------------------------------
ring:
#------------------------------------------------------------------------------
  username: !secret ring_user
  password: !secret ring_password
#------------------------------------------------------------------------------
sensor:
#------------------------------------------------------------------------------
  - platform: ring
#------------------------------------------------------------------------------
binary_sensor:
#------------------------------------------------------------------------------
  - platform: ring
camera:
  - platform: ring
  - platform: ffmpeg
    name: last_ring_video
    input: https://192.168.1.101:8123/local/last.mpg
#------------------------------------------------------------------------------
automation:
#------------------------------------------------------------------------------
  - alias: 'Doorbell Motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'off'
        to: 'on'
    action:
      - service: downloader.download_file
        data_template:
          url: "{{ states.camera.front_door.attributes.video_url }}"
          filename: "last.mpg"
          overwrite: true
      - service: notify.notify
        data:
          message: "Movimento davanti al cancello."
      - service: script.nabaztag_talk
        data:
          message: "C'è movimento davanti al cancello "
#******************************************************************************
  - alias: 'Doorbell Ding'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_ding
        from: 'off'
        to: 'on'
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.chromecastaudiosalotto
          media_content_type: "AUDIO"
          media_content_id: !secret doorbell-1
      - service: notify.notify
        data:
          message: "Campanello!"
      - service: script.nabaztag_talk
        data:
          message: "Qualcuno ha suonato il campanello"
#******************************************************************************